# Generated by Django 3.1.6 on 2021-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
