# Generated by Django 3.1.6 on 2021-04-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_register_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_url',
        ),
    ]
