# Generated by Django 3.1.6 on 2021-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='register_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
